before_install:
  - git lfs pull
  - sudo apt-get update
  - sudo apt-get install -y syslinux cmake libcap-dev libbz2-dev zlib1g-dev
  - pushd vendor
  - tar -xvf cdrkit-1.1.11-fedora29-patched.tar.gz
  - pushd cdrkit-1.1.11
  - mkdir build
  - pushd build
  - cmake ..
  - make
  - popd
  - popd
  - popd
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
script:
  - PATH=vendor/cdrkit-1.1.11/build/genisoimage:$PATH LD_LIBRARY_PATH=vendor/cdrkit-1.1.11/build/libusal/:vendor/cdrkit-1.1.11/build/librols:$LD_LIBRARY_PATH PYCDLIB_TRACK_WRITES=1 py.test --verbose tests
